### ISSUE TITLE
Add identifiers for all relations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [obophenotype/biological-spatial-ontology#1] opened 2015-04-07 19:10 UTC
```

Transferred from: 
https://sourceforge.net/p/obo/common-anatomy-reference-ontology-caro-requests/3/

```

Original issue reported on code.google.com by `cmung...@gmail.com` on 13 Jun 2013 at 4:21

**Comment by ramonawalls** [comment] 2020-11-04 17:23
I don't know if the issue is relevant to BSPO. Looks like it was imported from the CARO issue tracker.

@cmungall I don't suppose you have a memory of what it is?

**Comment by matentzn** [comment] 2020-11-04 17:37
Just close it.. if it's important it will be reopened..

**Closed** 2020-11-04 17:59 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
